### ISSUE TITLE
App Crashes after listening input ( FATAL EXCEPTION: AsyncTask )

### ISSUE THREAD

**Issue by Aashit-Sharma** [api-ai/apiai-android-client#45]
After following every step carefully from the tutorial (https://github.com/api-ai/apiai-android-client#tutorial)
The app crashes after it listens to my request.

Here is the monitor log, please help.
` FATAL EXCEPTION: AsyncTask #3
                                                                       Process: com.hai.aashit.homeai, PID: 15096
                                                                       java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                           at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                           at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                           at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                           at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                           at java.lang.Thread.run(Thread.java:818)
                                                                        Caused by: java.lang.NumberFormatException: Invalid int: "simple_response"
                                                                           at java.lang.Integer.invalidInt(Integer.java:138)
                                                                           at java.lang.Integer.parse(Integer.java:410)
                                                                           at java.lang.Integer.parseInt(Integer.java:367)
                                                                           at java.lang.Integer.parseInt(Integer.java:334)
                                                                           at com.google.gson.JsonPrimitive.getAsInt(JsonPrimitive.java:260)
                                                                           at ai.api.GsonFactory$ResponseItemAdapter.deserialize(GsonFactory.java:78)
                                                                           at ai.api.GsonFactory$ResponseItemAdapter.deserialize(GsonFactory.java:71)
                                                                           at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
                                                                           at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
                                                                           at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
                                                                           at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
                                                                           at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
                                                                           at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
                                                                           at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
                                                                           at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
                                                                           at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
                                                                           at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
                                                                           at com.google.gson.Gson.fromJson(Gson.java:887)
                                                                           at com.google.gson.Gson.fromJson(Gson.java:852)
                                                                           at com.google.gson.Gson.fromJson(Gson.java:801)
                                                                           at com.google.gson.Gson.fromJson(Gson.java:773)
                                                                           at ai.api.AIDataService.request(AIDataService.java:193)
                                                                           at ai.api.AIDataService.request(AIDataService.java:148)
                                                                           at ai.api.services.GoogleRecognitionServiceImpl$2.doInBackground(GoogleRecognitionServiceImpl.java:166)
                                                                           at ai.api.services.GoogleRecognitionServiceImpl$2.doInBackground(GoogleRecognitionServiceImpl.java:158)
                                                                           at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                           at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                           at java.lang.Thread.run(Thread.java:818)`

**Comment by Aashit-Sharma** [comment]
@xVir @artemgoncharuk @sstepashka @GusarovRB

**Comment by android-saurabhjain** [comment]
I have also face the same issue, which is not resolved till yet.

**Comment by folomeev** [comment]
The issue was [fixed in Java SDK](https://github.com/api-ai/apiai-java-client/issues/24) and will be available on next release.
